server:
  port: 8082

spring:
  application:
    name: doctor-service

  datasource:
    url: jdbc:postgresql://localhost:5432/med-personal
    username: postgres
    password: KuzPsina
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      password: zp5mXl2Xg5pxl8YI14kXy6hjlEHXKACr
      username: "default"
      host: redis-11585.c239.us-east-1-2.ec2.redns.redis-cloud.com:11585

application:
  security:
    jwt:
      secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
      expiration: 86400000


logging:
  level:
    org:
      springframework:
        security: trace

askep:
  store:
    file-path: D:\PetProjects\AskepClone\askep-medical-system\med-personal-service\src\main\resources\static

